"""
Ticker dictionary: maps stock ticker symbols -> company names.
Includes S&P 500 components + popular WSB/meme stocks.
Words that are common English words are excluded to reduce false positives.
"""

# Common English words that overlap with real tickers — skip these
BLACKLIST = {
    "A", "I", "IT", "IS", "BE", "AT", "OR", "ARE", "FOR",
    "ALL", "CAN", "NOW", "GET", "HAS", "HAD", "HIM", "HER",
    "THE", "AND", "BUT", "NOT", "OUT", "USE", "ONE", "TWO",
    "GO", "DO", "SO", "US", "ON", "IN", "TO", "OF", "BY",
    "CEO", "CFO", "COO", "IPO", "ETF", "GDP", "CPI", "SEC",
    "DD", "OP", "OG", "EV", "AI", "BIG", "LOW", "HIGH",
    "NEW", "OLD", "ANY", "FYI", "IMO", "TBH", "RN", "GG",
    "lol", "wow", "yes", "no",
    "EDIT", "TLDR", "ATH", "ATL", "EOD", "EOY", "YTD",
    "PM", "AM", "CA", "UK", "EU", "WSB", "RH", "WS",
    "LOSS", "GAIN", "YOLO", "FOMO", "HODL", "FUD",
    "CALLS", "PUTS", "CALL", "PUT", "BUY", "SELL",
    "LONG", "SHORT", "BEAR", "BULL", "MOON", "DUMP",
    "PUMP", "HOLD", "NEXT", "BACK", "LOOK", "MAKE",
    "GOOD", "BEST", "JUST", "ALSO", "MUCH", "VERY",
    "WELL", "REAL", "WILL", "NEED", "WANT", "KNOW",
    "LIKE", "FEEL", "GIVE", "SHOW", "KEEP", "PLAY",
    "MOVE", "WORK", "TIME", "YEAR", "WEEK", "DAYS",
    "DAY", "WAY", "MAN", "END", "OFF", "OVER", "DOWN",
    "ONLY", "THEN", "WHEN", "INTO", "THAN", "MOST",
    "BOTH", "WELL", "SAME", "EVEN", "SUCH", "WHAT",
    "THEM", "THEY", "SOME", "FROM", "WITH", "MORE",
    "BEEN", "HAVE", "THAT", "THIS", "WERE", "YOUR",
    "CASH", "RATE", "RISK", "FUND", "DEBT", "BOND",
    "GOLD", "SILVER", "OIL", "GAS",
}

TICKERS = {
    # ── Mega-cap / widely-held ────────────────────────────────────────────
    "AAPL":  "Apple Inc.",
    "MSFT":  "Microsoft Corporation",
    "GOOGL": "Alphabet Inc. (Class A)",
    "GOOG":  "Alphabet Inc. (Class C)",
    "AMZN":  "Amazon.com Inc.",
    "META":  "Meta Platforms Inc.",
    "TSLA":  "Tesla Inc.",
    "NVDA":  "NVIDIA Corporation",
    "NFLX":  "Netflix Inc.",
    "BRKB":  "Berkshire Hathaway (Class B)",
    "BRKA":  "Berkshire Hathaway (Class A)",
    "JPM":   "JPMorgan Chase & Co.",
    "V":     "Visa Inc.",
    "MA":    "Mastercard Inc.",
    "UNH":   "UnitedHealth Group",
    "JNJ":   "Johnson & Johnson",
    "XOM":   "Exxon Mobil Corporation",
    "WMT":   "Walmart Inc.",
    "PG":    "Procter & Gamble Co.",
    "LLY":   "Eli Lilly and Company",
    "HD":    "Home Depot Inc.",
    "CVX":   "Chevron Corporation",
    "MRK":   "Merck & Co.",
    "ABBV":  "AbbVie Inc.",
    "PEP":   "PepsiCo Inc.",
    "KO":    "Coca-Cola Company",
    "COST":  "Costco Wholesale",
    "AVGO":  "Broadcom Inc.",
    "MCD":   "McDonald's Corporation",
    "CRM":   "Salesforce Inc.",
    "ACN":   "Accenture PLC",
    "TMO":   "Thermo Fisher Scientific",
    "LIN":   "Linde PLC",
    "NEE":   "NextEra Energy",
    "TXN":   "Texas Instruments",
    "DHR":   "Danaher Corporation",
    "PM":    "Philip Morris International",
    "BMY":   "Bristol-Myers Squibb",
    "AMGN":  "Amgen Inc.",
    "RTX":   "Raytheon Technologies",
    "HON":   "Honeywell International",
    "QCOM":  "Qualcomm Inc.",
    "SBUX":  "Starbucks Corporation",
    "GE":    "General Electric",
    "AMD":   "Advanced Micro Devices",
    "INTC":  "Intel Corporation",
    "IBM":   "International Business Machines",
    "ORCL":  "Oracle Corporation",
    "NOW":   "ServiceNow Inc.",
    "INTU":  "Intuit Inc.",
    "AMAT":  "Applied Materials",
    "LRCX":  "Lam Research",
    "MU":    "Micron Technology",
    "KLAC":  "KLA Corporation",
    "ADI":   "Analog Devices",
    "MRVL":  "Marvell Technology",
    "NXPI":  "NXP Semiconductors",
    "ON":    "ON Semiconductor",
    "SWKS":  "Skyworks Solutions",
    "QRVO":  "Qorvo Inc.",
    "TER":   "Teradyne Inc.",
    # ── Financials ────────────────────────────────────────────────────────
    "BAC":   "Bank of America",
    "WFC":   "Wells Fargo",
    "GS":    "Goldman Sachs",
    "MS":    "Morgan Stanley",
    "C":     "Citigroup Inc.",
    "BLK":   "BlackRock Inc.",
    "AXP":   "American Express",
    "SCHW":  "Charles Schwab",
    "USB":   "U.S. Bancorp",
    "PNC":   "PNC Financial Services",
    "TFC":   "Truist Financial",
    "COF":   "Capital One Financial",
    "CB":    "Chubb Limited",
    "MMC":   "Marsh & McLennan",
    "AON":   "Aon PLC",
    "ICE":   "Intercontinental Exchange",
    "CME":   "CME Group",
    "SPGI":  "S&P Global",
    "MCO":   "Moody's Corporation",
    "FIS":   "Fidelity National Information",
    "FISV":  "Fiserv Inc.",
    "PYPL":  "PayPal Holdings",
    "SQ":    "Block Inc.",
    "HOOD":  "Robinhood Markets",
    "COIN":  "Coinbase Global",
    # ── Healthcare / Biotech ──────────────────────────────────────────────
    "PFE":   "Pfizer Inc.",
    "MRNA":  "Moderna Inc.",
    "BNTX":  "BioNTech SE",
    "GILD":  "Gilead Sciences",
    "REGN":  "Regeneron Pharmaceuticals",
    "VRTX":  "Vertex Pharmaceuticals",
    "BIIB":  "Biogen Inc.",
    "ILMN":  "Illumina Inc.",
    "IDXX":  "IDEXX Laboratories",
    "EW":    "Edwards Lifesciences",
    "DXCM":  "Dexcom Inc.",
    "ISRG":  "Intuitive Surgical",
    "HCA":   "HCA Healthcare",
    "CI":    "Cigna Group",
    "CVS":   "CVS Health",
    "MCK":   "McKesson Corporation",
    "ABC":   "AmerisourceBergen",
    "CAH":   "Cardinal Health",
    "ZBH":   "Zimmer Biomet",
    "BAX":   "Baxter International",
    # ── Consumer / Retail ─────────────────────────────────────────────────
    "AMZN":  "Amazon.com Inc.",
    "TGT":   "Target Corporation",
    "LOW":   "Lowe's Companies",
    "TJX":   "TJX Companies",
    "ROST":  "Ross Stores",
    "DLTR":  "Dollar Tree",
    "DG":    "Dollar General",
    "KR":    "Kroger Co.",
    "SYY":   "Sysco Corporation",
    "YUM":   "Yum! Brands",
    "CMG":   "Chipotle Mexican Grill",
    "DPZ":   "Domino's Pizza",
    "DKNG":  "DraftKings Inc.",
    "NKE":   "Nike Inc.",
    "VFC":   "VF Corporation",
    "PVH":   "PVH Corp.",
    "RL":    "Ralph Lauren",
    "TPR":   "Tapestry Inc.",
    "CPRI":  "Capri Holdings",
    "EL":    "Estee Lauder",
    "ULTA":  "Ulta Beauty",
    # ── Energy ───────────────────────────────────────────────────────────
    "COP":   "ConocoPhillips",
    "EOG":   "EOG Resources",
    "SLB":   "Schlumberger",
    "HAL":   "Halliburton",
    "BKR":   "Baker Hughes",
    "MPC":   "Marathon Petroleum",
    "VLO":   "Valero Energy",
    "PSX":   "Phillips 66",
    "OXY":   "Occidental Petroleum",
    "DVN":   "Devon Energy",
    "FANG":  "Diamondback Energy",
    "PXD":   "Pioneer Natural Resources",
    "HES":   "Hess Corporation",
    "APA":   "APA Corporation",
    "MRO":   "Marathon Oil",
    # ── Tech / Software / Cloud ───────────────────────────────────────────
    "ADBE":  "Adobe Inc.",
    "SNOW":  "Snowflake Inc.",
    "PLTR":  "Palantir Technologies",
    "PATH":  "UiPath Inc.",
    "DDOG":  "Datadog Inc.",
    "NET":   "Cloudflare Inc.",
    "CRWD":  "CrowdStrike Holdings",
    "ZS":    "Zscaler Inc.",
    "OKTA":  "Okta Inc.",
    "MDB":   "MongoDB Inc.",
    "TEAM":  "Atlassian Corporation",
    "ZM":    "Zoom Video Communications",
    "DOCU":  "DocuSign Inc.",
    "TWLO":  "Twilio Inc.",
    "U":     "Unity Software",
    "RBLX":  "Roblox Corporation",
    "SNAP":  "Snap Inc.",
    "PINS":  "Pinterest Inc.",
    "TWTR":  "Twitter / X Corp.",
    "LYFT":  "Lyft Inc.",
    "UBER":  "Uber Technologies",
    "ABNB":  "Airbnb Inc.",
    "DASH":  "DoorDash Inc.",
    "SPOT":  "Spotify Technology",
    "TTD":   "The Trade Desk",
    "ROKU":  "Roku Inc.",
    "SQ":    "Block Inc.",
    "AFRM":  "Affirm Holdings",
    "UPST":  "Upstart Holdings",
    "OPEN":  "Opendoor Technologies",
    "SOFI":  "SoFi Technologies",
    # ── EV / Clean Energy ─────────────────────────────────────────────────
    "RIVN":  "Rivian Automotive",
    "LCID":  "Lucid Group",
    "NIO":   "NIO Inc.",
    "XPEV":  "XPeng Inc.",
    "LI":    "Li Auto Inc.",
    "FSR":   "Fisker Inc.",
    "NKLA":  "Nikola Corporation",
    "CHPT":  "ChargePoint Holdings",
    "BLNK":  "Blink Charging",
    "EVGO":  "EVgo Inc.",
    "PLUG":  "Plug Power Inc.",
    "FCEL":  "FuelCell Energy",
    "BE":    "Bloom Energy",
    "ENPH":  "Enphase Energy",
    "SEDG":  "SolarEdge Technologies",
    "SUNR":  "SunRun Inc.",
    "RUN":   "Sunrun Inc.",
    # ── WSB Meme / Popular ────────────────────────────────────────────────
    "GME":   "GameStop Corp.",
    "AMC":   "AMC Entertainment Holdings",
    "BB":    "BlackBerry Limited",
    "NOK":   "Nokia Corporation",
    "BBBY":  "Bed Bath & Beyond",
    "KOSS":  "Koss Corporation",
    "EXPR":  "Express Inc.",
    "CLOV":  "Clover Health Investments",
    "WKHS":  "Workhorse Group",
    "SPCE":  "Virgin Galactic Holdings",
    "WISH":  "ContextLogic Inc.",
    "UWMC":  "UWM Holdings",
    "RKT":   "Rocket Companies",
    "TLRY":  "Tilray Brands",
    "CGC":   "Canopy Growth Corporation",
    "ACB":   "Aurora Cannabis",
    "SNDL":  "SNDL Inc.",
    "MMAT":  "Meta Materials Inc.",
    "NAKD":  "Naked Brand Group",
    "CTRM":  "Castor Maritime",
    "VLDR":  "Velodyne Lidar",
    "ARVL":  "Arrival SA",
    "GOEV":  "Canoo Inc.",
    "RIDE":  "Lordstown Motors",
    "FFIE":  "Faraday Future",
    "MULN":  "Mullen Automotive",
    "ATER":  "Aterian Inc.",
    "BBIG":  "Vinco Ventures",
    "PROG":  "Progenity Inc.",
    "SDC":   "SmileDirectClub",
    "SPRT":  "Support.com",
    "IRBT":  "iRobot Corporation",
    "BYND":  "Beyond Meat",
    "OATLY": "Oatly Group",
    "AMC":   "AMC Entertainment",
    # ── Defense / Aerospace ───────────────────────────────────────────────
    "LMT":   "Lockheed Martin",
    "NOC":   "Northrop Grumman",
    "GD":    "General Dynamics",
    "BA":    "Boeing Company",
    "LHX":   "L3Harris Technologies",
    "HII":   "Huntington Ingalls",
    "LDOS":  "Leidos Holdings",
    "SAIC":  "Science Applications International",
    "TDG":   "TransDigm Group",
    "HEI":   "HEICO Corporation",
    # ── Industrials ───────────────────────────────────────────────────────
    "MMM":   "3M Company",
    "CAT":   "Caterpillar Inc.",
    "DE":    "Deere & Company",
    "EMR":   "Emerson Electric",
    "ETN":   "Eaton Corporation",
    "ITW":   "Illinois Tool Works",
    "PH":    "Parker-Hannifin",
    "ROK":   "Rockwell Automation",
    "IR":    "Ingersoll Rand",
    "AME":   "AMETEK Inc.",
    "FTV":   "Fortive Corporation",
    "ROP":   "Roper Technologies",
    "XYL":   "Xylem Inc.",
    "OTIS":  "Otis Worldwide",
    "CARR":  "Carrier Global",
    "LII":   "Lennox International",
    "MAS":   "Masco Corporation",
    "SWK":   "Stanley Black & Decker",
    "TT":    "Trane Technologies",
    "JCI":   "Johnson Controls",
    # ── Real Estate / REITs ───────────────────────────────────────────────
    "AMT":   "American Tower Corporation",
    "PLD":   "Prologis Inc.",
    "CCI":   "Crown Castle Inc.",
    "EQIX":  "Equinix Inc.",
    "PSA":   "Public Storage",
    "EXR":   "Extra Space Storage",
    "DLR":   "Digital Realty Trust",
    "O":     "Realty Income Corporation",
    "SBAC":  "SBA Communications",
    "AVB":   "AvalonBay Communities",
    "EQR":   "Equity Residential",
    "ESS":   "Essex Property Trust",
    "MAA":   "Mid-America Apartment",
    "UDR":   "UDR Inc.",
    "CPT":   "Camden Property Trust",
    # ── Communications / Media ────────────────────────────────────────────
    "T":     "AT&T Inc.",
    "VZ":    "Verizon Communications",
    "TMUS":  "T-Mobile US",
    "CMCSA": "Comcast Corporation",
    "CHTR":  "Charter Communications",
    "DIS":   "Walt Disney Company",
    "PARA":  "Paramount Global",
    "WBD":   "Warner Bros. Discovery",
    "FOX":   "Fox Corporation",
    "FOXA":  "Fox Corporation (Class A)",
    "NYT":   "New York Times Company",
    # ── Crypto-adjacent ───────────────────────────────────────────────────
    "MSTR":  "MicroStrategy Inc.",
    "RIOT":  "Riot Platforms",
    "MARA":  "Marathon Digital Holdings",
    "HUT":   "Hut 8 Mining",
    "BITF":  "Bitfarms Ltd.",
    "BTBT":  "Bit Digital Inc.",
    "CIFR":  "Cipher Mining",
    "WULF":  "TeraWulf Inc.",
}

# Remove any tickers that are in the blacklist
TICKERS = {k: v for k, v in TICKERS.items() if k.upper() not in BLACKLIST}


def get_ticker_dict() -> dict:
    """Return the ticker -> company name dictionary."""
    return TICKERS


def get_blacklist() -> set:
    """Return the set of words to ignore even if they match a ticker."""
    return BLACKLIST
